[project]
name = "semantic-piv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "dotenv>=0.9.9",
    "openai>=2.15.0",
    "pyshacl>=0.31.0",
]
